name: Deploy to GitHub Pages
env:
  BUILD_PATH: dist
on:
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          yarn install
      - name: Generate types
        run: |
          npx hardhat typechain
      - name: Build
        run: |
          yarn build
          cp $BUILD_PATH/index.html $BUILD_PATH/404.html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.BUILD_PATH }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
