name: Slither Audit
on:
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Slither
        uses: crytic/slither-action@v0.3.0
        with:
          node-version: '20'
          fail-on: 'medium'
          target: 'src/contracts'
